### PR TITLE
fix #220: include tabId in browserAction.set* calls

### LINKED ISSUE #220: Facebook Container's panel displays misleading information on non-Facebook pages
**[Affected versions]:**

- Firefox 65.0.2 (BuildId:20190225143501).

**[Affected Platforms]:**

- Windows 10 64bit
- macOS 10.13
- Ubuntu 16.04 64bit

**[Steps to reproduce]:**

1. Launch Firefox.
2. Install Facebook Container 1.6.0
3. Access the https://www.wikipedia.org/ webpage.
4. Access the https://www.facebook.com webpage in a new tab.
5. Switch back to the Wikipedia tab **before Facebook page successfully loads**.
6. Click on the Facebook Container toolbar button.

**[Expected result]:**

The information from the Facebook Container's panel states that Wikipedia **is not** in the Facebook Container. 

**[Actual result]:**

The information from the Facebook Container's panel states that Wikipedia **is** in the Facebook Container. 

**[Additional Notes]:**

- Please note that the correct String is displayed if the user refreshes the Wikipedia page before opening the Facebook Container panel or if the user waits for the Facebook page to fully load.
- Attached screenshots for this:.

bg

### PR DESCRIPTION
**Pull request by groovecoder**
I'm also doing double-duty in this PR by adding/restoring the Facebook briefcase icon in the pop-up. I noticed that "This icon" was in the copy, but we forgot to include the icon! It's there now ...

image

### CODE REVIEW

**Comment by groovecoder** [comment]
Pinging lots of folks for review, but really just need 1. Just trying to get a review & merge done by EOD so I can build & sign a new release candidate for QA tomorrow.

File: src/background.js [hunk 1]
```diff
@@ -323,7 +323,7 @@ function stripFbclid(url) {
 }
 
 async function tabUpdateListener (tabId, changeInfo, tab) {
-  await updateBrowserActionIcon(tab.url);
+  await updateBrowserActionIcon(tab);
```
Comment (stoically) [inline src/background.js]: Just a side note: it would be probably enough to call `updateBrowserActionIcon` when `changeInfo.url` is set. Other than that the PR looks good to me.

Comment (groovecoder) [reply src/background.js]: Taking the r+ whiel I can get it. 😄
