### PR TITLE
Fixed #588 - Added logic to stop about: pages from being added to the container

### LINKED ISSUE #588: "about:" pages can be added to FBC, the titles are displayed as empty in the list and they can't be removed
- Facebook Container Version: 2.1.0
- Affected platforms:
      - Windows 10 x64
      - MacOS 10.15
      - Ubuntu 18.04

### Steps to reproduce
1. Add Facebook Container 2.1.0 to Firefox
2. Open any about: page in new tab (e.g about:support)
3. Allow the page in FBC
4. Click the Facebook Container icon and select "Sites Allowed in Facebook Container"

### Actual behavior
1. The page is added to list but the page title is displayed as empty
2. The page remains in the list after removing it from FBC
3. A new entry containing the add-on UUID is added to list after every Remove attempt

### Expected behavior
1. The page titles should be displayed in the Allowed list 
2. The about: pages should be removable from FBC
3. No new items should appear in the allowed list after remove operation 
 
OR

   The user should not be able to add "about:" pages to FBC

### Notes
See the attached screenshot
aboutPageAdded

### PR DESCRIPTION
**Pull request by maxxcrawford**
## Testing steps

- Navigate to any about: page (ex: `about:about`)
- Open panel, try to click on "Allow Site in Facebook Container"
- **Expected**: Button is grayed out, clicking does nothing

image

### CODE REVIEW

File: src/background.js [hunk 1]
```diff
@@ -432,8 +432,7 @@ async function updateBrowserActionIcon (tab) {
 
   const url = tab.url;
   const hasBeenAddedToFacebookContainer = await isAddedToFacebookContainer(url);
-
-
+  const aboutPageURLCheck = url.indexOf("about:");
```
Comment (groovecoder) [inline src/background.js]:
```suggestion
  const aboutPageURLCheck = url.startsWith("about:");
```

So we don't get false positives on pages like https://wiki.mozilla.org/Firefox/Projects/about:newtab.

File: src/background.js [hunk 2]
```diff
@@ -442,6 +441,9 @@ async function updateBrowserActionIcon (tab) {
     browser.browserAction.setPopup({tabId: tab.id, popup: "./panel.html"});
   } else if (hasBeenAddedToFacebookContainer) {
     browser.storage.local.set({"CURRENT_PANEL": "in-fbc"});
+  } else if (aboutPageURLCheck > -1) {
```
Comment (groovecoder) [inline src/background.js]:
```suggestion
  } else if (aboutPageURLCheck) {
```
