### PR TITLE
Fixed #585 - Added confirmation interstitial when adding/removing sites from the container 

### LINKED ISSUE #585: Door hangers are not displayed for "Allow" and "Remove" functions
**Affected versions**
* Firefox 74.0b4

**Affected platforms**
* Windows 10 x64
* macOS 10.15
* Ubuntu 18.04 x64

**Steps to reproduce**
1. Download [Facebook Container 2.1.0](https://github.com/mozilla/contain-facebook/releases/tag/2.1.0) .zip file and extract it.
2. Launch Firefox and go to `about:debugging#/runtime/this-firefox`.
3. Click on "Load Temporary Add-on...", then select `manifest.json` from the extracted archived.
4. Navigate to https://www.google.com/ in a new tab.
5. From the Url toolbar, click on the Facebook Container icon.
6. Click on the "Allow Site in Facebook Container" option.

**Expected result**
* A FBC door hanger is displayed with the "Allow" button, as per specs:

image

image

**Actual result**
* There is no confirmation door hanger displayed after allowing or removing a website from FBC.

### PR DESCRIPTION
**Pull request by maxxcrawford**
Fixes #585 

Added interstitial confirmation panel when adding site to the container.
Revised flow to include confirmation panel when removing site, if triggered from the main panel (and not the site list manager panel)

Reference: 
- [InVision Spec](https://mozilla.invisionapp.com/share/WNREP95GJ4V#/387099855_Sites_Allowed_Into_FBC)

### Adding Site: 
- Navigate to any non-FB container site in browser (Ex: firefox.com) 
- Open panel, click "Allow Site in Facebook Container"
- Expected: See "Allow" confirmation panel. 

image

### Removing Site: 
- Navigate to any CUSTOM CONTAINED SITE inside the FB container site
- Open panel, click "Remove Site from Facebook Container" 
- Expected: See "Remove" confirmation panel (Exactly what is shown when going to "Sites Allowed in Facebook Container" > Clicking "X" on _Sites You've Allowed_ list) 

image

image

### CODE REVIEW

File: src/panel.js [hunk 1]
```diff
@@ -529,20 +529,50 @@ const buildAllowedSitesPanel = async(panelId) => {
 
 const removeSiteFromContainer = async () => {
   const activeHostname = await getActiveHostname();
-  await browser.runtime.sendMessage( {removeDomain: activeHostname} );
-  browser.tabs.reload();
-  window.close();
+  buildRemoveSitePanel(activeHostname);
```
Comment (maxxcrawford) [inline src/panel.js]: Added "remove site" interstitial that was already in use in the site listed panel: 

image

File: src/panel.js [hunk 2]
```diff
@@ -529,20 +529,50 @@ const buildAllowedSitesPanel = async(panelId) => {
...
+  if (!activeHostname) { throw new Error("Missing site name. Cannot add site."); }
   const fbcStorage = await browser.storage.local.get();
   fbcStorage.domainsAddedToFacebookContainer.push(activeHostname);
   await browser.storage.local.set({"domainsAddedToFacebookContainer": fbcStorage.domainsAddedToFacebookContainer});
   browser.tabs.reload();
   window.close();
 };
 
+const buildAddSitePanel = async (siteName) => {
+  if (!siteName) {
```
Comment (maxxcrawford) [inline src/panel.js]: This accounts for adding a site from the first panel, where this data element has not be defined.

File: src/panel.css [hunk 3]
```diff
@@ -221,7 +221,7 @@ a:hover {
   transition: var(--transition);
 }
 
-.remove-btn {
+.remove-btn, .allow-btn {
```
Comment (maxxcrawford) [inline src/panel.css]: All the CSS changes were extending the classes already defined for the remove panel.

File: src/panel.js [hunk 4]
```diff
@@ -529,20 +529,50 @@ const buildAllowedSitesPanel = async(panelId) => {
...
+  const panelId = "add-site";
+  const { page, fragment } = setUpPanel(panelId);
+
+  addHeaderWithBackArrow(fragment);
+
+  const contentWrapper = addDiv(fragment, "main-content-wrapper");
+  contentWrapper.classList.add("remove-site-panel");
+
+  addSubhead(contentWrapper, "add-site");
+  makeSiteList(contentWrapper, [siteName], true, false); // (..., sitesAllowed=true, addX=false )
```
Comment (groovecoder) [inline src/panel.js]: omg ❤️ the inline comment for the args.

**Comment by groovecoder** [comment]
Looks good, but needs a conflict resolution?
