### PR TITLE
Content Script Fixes (Adding Site Selector, Minor Changes) 

### LINKED ISSUE #328: Some Facebook buttons are said to be disabled even though they don't track and still work
I visited this page: https://theintercept.com/2019/05/09/watch-interview-with-democratic-congresswoman-and-2020-presidential-candidate-tulsi-gabbard/

And saw this:
image

But if I click on the Facebook button, it opens a popup that lets me share the page to Facebook.

I would suggest either
* not badging the button at all
* badging the button, but with a message that says "Facebook Container has confirmed that this Facebook button is not tracking you."

### LINKED ISSUE #334: On yelp there is no badge for Sign up button, but there is one for Log in button
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
 - Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**

1. Go to https://www.yelp.com/.
2. Click on the Sign Up button and observe the behaviour.
3. Switch to the Log In page and observe the behaviour.

**Expected result:**
- On both of the pages there are badges present on the related Facebook buttons. 

**Actual result:**
- There is no badge on Sign up page, but there is one on Log in one. 

**Notes:**
- Please see the attached screen recording with the issue: 
https://drive.google.com/open?id=1_Ki5QXyI6SBOBOQfLZEOpXq1CUnDyHF1

### LINKED ISSUE #336: The login with facebook buttons are not actionable on Hi5
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
- Windows 7 x64
- Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**

1. Go to [Hi5](https://secure.hi5.com/).
2. Click on either one of the two facebook login buttons.

**Expected result:**
- A popup requesting the user to login with the facebook account will be shown.

**Actual result:**
- Nothing happens.

**Notes:**
- Please see the attached screenshot with the two facebook buttons: 
2019-05-08 17_22_51-hi5 - The social network for meeting new people

### LINKED ISSUE #341: The badge for share buttons is not always displayed for certain websites
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
 - Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the latest [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**
1. Go to https://www.football.london/tottenham-hotspur-fc/fixtures-results/spurs-press-conference-live-mauricio-16255596
2. Inspect the Facebook share button.

**Expected result:**
- The Facebook share button has the badge properly displayed.

**Actual result:**
- The Facebook share button has no badge displayed.

**Notes:**
- Other websites affected by this issue: https://www.skysports.com/football/news/11667/11715959/manchester-united-to-close-agreeing-daniel-james-deal-from-swansea
- https://imgur.com/gallery/sPC8df5
- Please see the attached screenshot
Screenshot from 2019-05-10 17-05-13
 with the issue:

### LINKED ISSUE #343: FBC tool-tip appear as cut off on hovering
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
 - Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the latest [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**
1. Go to this [website](https://www.amazon.com/Longwu-Womens-Casual-Bandage-Blue-XL/dp/B07QTYVNRD/ref=lp_18665827011_1_1?srs=18665827011&ie=UTF8&qid=1557498392&sr=8-1).
2. Hover over the purple badge from the Facebook share button.

**Expected result:**
- FBC tool-tip is properly displayed.

**Actual result:**
- FBC tool-tip appear as cut off. 

**Notes:**
- Please see the attached screenshot:

Screenshot from 2019-05-10 17-35-02

### PR DESCRIPTION
**Pull request by maxxcrawford**
Fixed #343 
Fixed #341 
Fixed #336 
Fixed #334
Fixed #328 

Login detection now works on: 
+ https://hi5.com
+ https://yelp.com

Share detection now works on: 
+ https://imgur.com 
+ https://www.skysports.com
+ https://www.football.london

## Screenshots

image

### CODE REVIEW

File: src/content_script.js [hunk 1]
```diff
@@ -254,6 +274,19 @@ function checkVisibilityAndApplyClass(target, htmlBadgeDiv) {
...
 }
 
+function determineContainerClientRect() {
+  const htmlHeight = document.querySelector("html").offsetHeight;
+  const bodyHeight = document.querySelector("body").offsetHeight;
+  // console.log([htmlHeight, bodyHeight]);
+  if (htmlHeight === bodyHeight) {
+    return document.body.getBoundingClientRect();
+  } else if ( htmlHeight > bodyHeight ) {
+    return document.querySelector("html").getBoundingClientRect();
```
Comment (groovecoder) [inline src/content_script.js]: Could optimize by assigning this to a `const` up above ...
```js
const htmlElement = document.querySelector("html");
const htmlHeight = htmlElement.offsetHeight;
...
} else if ( htmlHeight > bodyHeight) {
  return htmlElement.getBoundingClientRect();
}
```
